### PR TITLE
resolves #149 use correct config for MathJax

### LINKED ISSUE #149: asciimath incorrect output
**Steps to reproduce**
1. Create document with content
```
= Math formulae

[asciimath]
++++
sum_(i=1)^n i^3=((n(n+1))/2)^2
++++
```
2. Open file in Chrome having asciidoctor-chrome-extension installed.

**Expected result**

  Formula displayed as follows (screenshot taken from mathjax.org)
should

**Actual result**

  Formula displayed as follows
is

### PR DESCRIPTION
**Pull request by mojavelinux**
- prevents AsciiMath expressions from being parsed as tex
- add missing message config

### CODE REVIEW

**Comment by mojavelinux** [comment]
I didn't add the Tex.equationNumbers.autoNumber setting since technically that isn't supported yet in core (as far as I remember). Best to leave that for a separate issue.

**Comment by Mogztter** [comment]
Thanks!
Maybe at some point we should use the constant defined in `asciidoctor.rb`:
https://github.com/asciidoctor/asciidoctor/blob/911d0bd509f369e9da15d2bb71f81aecb7c45fec/lib/asciidoctor.rb#L358-L361 or extract the MathJax config block in `html5.rb` as a constant.

**Comment by prudhomm** [comment]
@Mogztter is this fix in the last release ?

**Comment by Mogztter** [comment]
@prudhomm No this fix is currently only available on the master branch. I will do a bugfix release this week-end 😄

**Comment by Mogztter** [comment]
@prudhomm Do you have an example ? Because I cannot reproduce this issue and I want to create a unit test :wink:

**Comment by Mogztter** [comment]
[v1.5.5.112](https://github.com/asciidoctor/asciidoctor-browser-extension/releases/tag/v1.5.5.112) is published :tada:

**Pull request merged**
