### PR TITLE
Add tip about enabling local file access to options page

### LINKED ISSUE #92: Add tip about enabling local file access to options page
New users often forget to tick the `Allow access to file URLs` on the extension page. We should draw more attention to this advice.

Although the options page can't enable access to local files, we could use that screen to remind users about it using a callout (i.e., tip).

It also might be a good idea to draw more attention to this advice in the extension's description in the chrome store. I think we are limited to plain text, but we could surround it with `IMPORTANT!` so it's hard to miss.

### PR DESCRIPTION
**Pull request by Mogztter**
Resolves #92 

heads-up

### CODE REVIEW

**Comment by mojavelinux** [comment]
I like it!

**Comment by Mogztter** [comment]
Ok, is the sentence "To enable local file access, check `Allow access to file URLs` in chrome://extensions" clear enough ?

**Comment by mojavelinux** [comment]
Ah. How about:

"In order to use this extension on local files (i.e., files on this
computer), you must check the option “Allow access to file URLs” below this
extension at chrome://extensions.

You can leave out the clarification in brackets, but if you include it,
then it's definitely clear.

**Comment by Mogztter** [comment]
The link "chrome://extensions" automatically set focus on the Asciidoctor extension so I simplified the sentence to stay on one line:

> In order to use this extension on local files (i.e. files on this computer), you must check the option "Allow access to file URLs" on the "chrome://extensions" page

Is that OK ?

**Comment by mojavelinux** [comment]
Nice! Then what you propose is perfect!

**Pull request merged**
