### PR TITLE
Pass attributes as String

### LINKED ISSUE #128: setting custom attributes
It seems that when setting custom attributes with the options menu, that only the first one is detected and used. For example using the string

`skip-front-matter=1 attributeA=1`

it respects the skip-front-matter, but attributeA is not set
and using the string 

`attributeA=1 skip-front-matter=1`

do sets attributeA but ignores the skip-front-matter attribute.

Can anyone confirm this issue?

### PR DESCRIPTION
**Pull request by Mogztter**
Resolves #128

/cc @mojavelinux

### CODE REVIEW

**Comment by mojavelinux** [comment]
This works, but we're still leaving out some functionality. For instance, the Chrome extension won't be able to support spaces in an attribute name as it is currently being handled. It will likely get interpreted as separate attributes. (I haven't verified that, but that's what I gather from looking at the code).

I've brought up the idea of exposing an API to help process attributes that would be useful in scenarios like this.

**Comment by Mogztter** [comment]
I didn't know that we can have spaces in attribute names.
If the space is escaped, this should work no ?

Yes an API would be very useful.

Le 17 août 2016 12:17 AM, "Dan Allen" <notifications@github.com> a écrit :

This works, but we're still leaving out some functionality. For instance,
the Chrome extension won't be able to support spaces in an attribute name
as it is currently being handled. It will likely get interpreted as
separate attributes. (I haven't verified that, but that's what I gather
from looking at the code).

I've brought up the idea of exposing an API to help process attributes that
would be useful in scenarios like this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/asciidoctor/asciidoctor-chrome-extension/pull/134#issuecomment-240257109>,
or mute the thread

**Comment by mojavelinux** [comment]
If the space is escaped, this should work no ?
>

Yes, but doesn't the Chrome extension split on spaces somewhere. It might
be mangling the entries before they make it to the API. (or, that might not
be happening...I haven't looked in depth). That's why an API helper would
be really...helpful.

**Comment by Mogztter** [comment]
No we don't split on spaces anymore.

- Custom attributes (defined in the options page) are left unchanged as a
String.
- Default attributes are defined in the code and do not contain spaces.

However I didn't try to define an attribute with a space as a query
parameters.

I will do some tests :)

Le 17 août 2016 1:06 AM, "Dan Allen" <notifications@github.com> a écrit :

If the space is escaped, this should work no ?
>

Yes, but doesn't the Chrome extension split on spaces somewhere. It might
be mangling the entries before they make it to the API. (or, that might not
be happening...I haven't looked in depth). That's why an API helper would
be really...helpful.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/asciidoctor/asciidoctor-chrome-extension/pull/134#issuecomment-240266811>,
or mute the thread

**Comment by mojavelinux** [comment]
Excellent!

**Comment by Mogztter** [comment]
> For instance, the Chrome extension won't be able to support spaces in an attribute name

You mean attribute value ?
According to the [User Manual](
http://asciidoctor.org/docs/user-manual/#attribute-restrictions), the name cannot contain dots or spaces:

> The attribute name:
 * must be at least one character long,
 * must begin with a word character (A-Z, a-z, 0-9 or _) and
 * must only contain word characters and hyphens.

> In other words, the name cannot contain dots or spaces.

I did some tests and this is working great.

 * `attr-c` is a custom attribute defined in the options page and contains escaped space.
 * `attr-d` is a an extra attribute defined as a query parameter and contains escaped space.

```
= Attributes

Attribute A: {attr-a}

Attribute B: {attr-b}

Attribute C: {attr-c}

Attribute D: {attr-d}
```

attributes

attributes-uri

**Comment by mojavelinux** [comment]
> You mean attribute value ?

Yes, I meant value.

**Comment by mojavelinux** [comment]
Agreed, if the user does escape the spaces in the input, then in theory, if you join all the attributes from the Array and let core parse it again, it should work.

Ideally, the Chrome extension would pass the attributes as a Hash. I suppose the current solution works, that would just be a cleaner hand off.

**Comment by M3lkior** [comment]
I'm currently using your fix and it works. Thanks

**Comment by Mogztter** [comment]
> I'm currently using your fix and it works. Thanks

Excellent thanks for your feedback

> Ideally, the Chrome extension would pass the attributes as a Hash. I suppose the current solution works, that would just be a cleaner hand off.

Yes, passing the attributes as a Hash is what we want to do but I don't want to duplicate the space logic code in the Chrome extension.
When an API will be available in core, I will pass the attributes as a Hash.

**Pull request merged**
