### PR TITLE
Resolves #106, options page saves changes automatically

### LINKED ISSUE #106: Options page should save changes immediately / automatically
I think the option page should save changes immediately / automatically without having to click the Save button. In fact, we should remove the Save button. This is consistent with modern UX design, as far as I understand. I think it removes one layer of complexity for more novice users.

I think we just need to add some JavaScript events on the form fields to automatically submit the form via Ajax. Perhaps jQuery can help us with that.

Another option is to remove the Save button until it is needed, giving the user a hint as to when to click it.

### PR DESCRIPTION
**Pull request by Mogztter**
Every second I check if options changed, I don't know if this is the right approach. Maybe I should add listeners on every fields and save immediately. Text fields are a bit tricky because you need to wait for user to finish typing.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Checking every second is probably sufficient for most use cases, though ideally you'd want to use a listener on every field. I recommend creating a little framework that handles the callback so that you don't have lots of boilerplate (basically make an abstraction). It's a bit simpler knowing that the browser is Chrome, so you can rely on whatever behavior Chrome gives you.

**Comment by Mogztter** [comment]
I've create a little framework as suggested.
The usage is really simple, you just have to add `<span data-save-indicator="{input_name}"></span>` where you want.

This will create a save indicator for the input field:

save-indicator

save-indicator-saving

I could even refine the code and create a simple Bootstrap plugin to add save indicators on input fields :smile:

**Comment by mojavelinux** [comment]
Very cool! That looks great!

**Comment by Mogztter** [comment]
Options page are now embedded in a small popup and users need to scroll to see the save button.
This feature should improve the usability.

**Pull request merged**
