### PR TITLE
Allow attributes to be defined via URL parameters

### LINKED ISSUE #99: Allow attributes to be defined via URL parameters
Allow attributes to be defined ad-hoc, per document via URL parameters much like attributes are defined when using asciidoctor from the commandline.

Something like:

```
file:///path/to/my/doc.adoc?toc=preamble
```

I think we can use a single URL parameter per attribute to keep things simple.

### PR DESCRIPTION
**Pull request by Mogztter**
Resolves #99 

optimised

@mojavelinux Could you give it a try ?

### CODE REVIEW

**Comment by mojavelinux** [comment]
I love it! There are lots of use cases this is going to open up for the browser extensions. No longer will they be on the sidelines when it comes to context-specific path resolutions like includes.

Before we merge, there is one serious issue we need to address. We don't want to allow this to introduce an attack vector, so we need to do some cleansing of the values. Best to start conservative and work our way out.

Specifically, we should scrub (or escape) any HTML in the attribute value (and maybe in the future allow a subset). If you override an existing attribute that's used in the page, you can see it's possible to inject JavaScript or an iframe into the page.

Location bar
```
file:///path/to/file.adoc?project-version=<script>alert(%27hello!%27)<%2Fscript>
```

Document
```
{project-version}
```

I also wonder if we should put limits on the number of attributes and/or the size of an attribute value. For instance, we could limit the length of the attribute value to 256 characters to curb abuse. I'm not an expert in this field, so if you have other ideas, feel free to mention them.

**Comment by mojavelinux** [comment]
Btw, I love the screencasts that you add to your pull requests (esp for visual changes). Plus, it helps get more people interested and involved. I appreciate the extra effort!

**Comment by Mogztter** [comment]
> Before we merge, there is one serious issue we need to address. We don't want to allow this to introduce an attack vector, so we need to do some cleansing of the values. Best to start conservative and work our way out.

We can use JQuery to escape the "HTML" ?
```javascript
$('<div/>').text(queryParameter).html();
```

> Btw, I love the screencasts that you add to your pull requests (esp for visual changes)

I found this really simple tutorial on how to create animated gif of a screencast: http://askubuntu.com/questions/107726/how-to-create-animated-gif-images-of-a-screencast

We could even do something similar for the Asciidoctor README :smile:

**Comment by mojavelinux** [comment]
> We can use JQuery to escape the "HTML" ?

That should do it. If necessary, we'll adjust the strategy in the future if we get feedback that it's too conservative.

> I found this really simple tutorial on how to create animated gif of a screencast: http://askubuntu.com/questions/107726/how-to-create-animated-gif-images-of-a-screencast

Fantastic! Which tools do you use? I see that the tutorial has lots of suggestions.

> We could even do something similar for the Asciidoctor README 

I think there are places where this would work really well. We have to be careful that it doesn't distract from reading, so there are places where it's the right approach and places where it would get in the way. But perhaps we can do a "click to activate" or "touch to activate" to enable the animation (swap in the gif) so it happens when you want it, but not when you don't. We should discuss it as part of the docs conversation.

**Comment by Mogztter** [comment]
I'm using the tools mentioned by the accepted answer: http://askubuntu.com/a/107735

 * `recordmydesktop` creates an ogv video
 * `mplayer` captures JPEG screenshots of the video
 * `convert` (ImageMagick) converts the screenshots into an animated gifs

**Comment by mojavelinux** [comment]
Awesome. I really like that set of tools!

**Comment by mojavelinux** [comment]
I see you used a built-in way in HTML DOM to escape the value. Nice!

**Pull request merged**
