### PR TITLE
resolves #85 enable web fonts in asciidoctor theme

### LINKED ISSUE #85: Custom fonts from default stylesheet not being loaded
Now that we've gone offline, the custom fonts from the default stylesheet are not being loaded.

This is a case where I think we should just load the fonts from the web. The reason is, browsers already know how to deal with missing fonts gracefully, and we have reasonable fallbacks set.

We can take one of two approaches:

* Uncomment the font import statement in the bundled default stylesheet
* Implement the font injection logic that is done in the main converter (see https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L54)

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by Mogztter** [comment]
I think we need to find another way to load the fonts because Chrome extension CSP is too restrictive.

The same goes for embeded YouTube video...

**Comment by mojavelinux** [comment]
Can we just add it to permissions as described in this SO post? http://stackoverflow.com/questions/19210451/packaging-a-font-with-a-google-chrome-extension

**Comment by Mogztter** [comment]
Even with the following permission

```json
 "permissions":[
    "http://fonts.googleapis.com/",
    "https://fonts.googleapis.com/"
  ],
```
 I still get:
```
Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400ital…0,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
```

And if I append the following `<link>` to the `<head>` instead of the `@import`:
```html
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400' rel='stylesheet' type='text/css'>
```

I get:

```
Refused to load the font 'https://fonts.gstatic.com/s/droidsansmono/v7/ns-m2xQYezAtqh7ai59hJYdJ2JT0J65PSe7wdxAnx_I.woff2' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.
Refused to load the font 'https://fonts.gstatic.com/s/notoserif/v4/Q47Ro23nlKqZrOLipd3-SyEAvth_LlrfE80CYdSH47w.woff2' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.
Refused to load the font 'https://fonts.gstatic.com/s/notoserif/v4/qkE6YsKPRiYUugBb1_QwHCEAvth_LlrfE80CYdSH47w.woff2' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.
Refused to load the font 'https://fonts.gstatic.com/s/notoserif/v4/N2U74xxQEyaTBF6QLZRr1CEAvth_LlrfE80CYdSH47w.woff2' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.
Refused to load the font 'https://fonts.gstatic.com/s/notoserif/v4/1_daFS3X6gkNOcmGmHl7UiEAvth_LlrfE80CYdSH47w.woff2' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by mojavelinux** [comment]
It works for me when using an unpacked extension. Are you testing it packed
or unpacked when you get the error?

**Comment by Mogztter** [comment]
I am testing with packed extension and remote document hosted on GitHub.
No error is thrown when viewing local document.
But even with the console full of errors I can't see the difference in the
rendered document...

Are you experiencing the same behavior ?

**Comment by mojavelinux** [comment]
Aha, I forgot to test the remote URLs. That explains why I wasn't seeing the error.

I have searched and searched and I can't seem to find any confirmation that loading Google Fonts in a Google Chrome extension works, even with permissions or the content_security_policy set (I tried all sorts of combinations). An engineer in Google Fonts needs to have a stroll down the hall to visit an engineer on the Chrome team and figure out what the heck is going on over there. This has to be possible.

I'm going to ping Twitter for some answers. I guess we could also look for another extension that uses web fonts.

Note that the individual fonts are loaded from fonts.gstatic.com rather than fonts.googleapis.com, so we are dealing with two base URLs.

**Comment by Mogztter** [comment]
> I'm going to ping Twitter for some answers. I guess we could also look for another extension that uses web fonts.

Any news ?

> Note that the individual fonts are loaded from fonts.gstatic.com rather than fonts.googleapis.com, so we are dealing with two base URLs.

Yes I tried every combination but still not working...

**Comment by mojavelinux** [comment]
No news. Quite frustrating that it doesn't just work.

I'm ready at this point to resort to using JavaScript. Surely there must be some way to force fonts to resolve after the page loads. There's a Google Web Font preview extension that must be doing something like this. Perhaps it's time to study that source code.

**Comment by mojavelinux** [comment]
Here's code that loads fonts dynamically:

https://github.com/pamelafox/font-previewer-extension/blob/master/popup.js#L257

We have to know which fonts are loaded per theme, but for now we can just do this for the default theme...or we maintain a map of fonts that need to be loaded per theme.

**Pull request merged**
