### PR TITLE
Restructure project

### PR DESCRIPTION
**Pull request by Mogztter**
* Remove Grunt (copy task was not working anymore)
* Add eslint
* Add yarn.lock
* Add .editorconfig
* Update README to include a "Contributing" section
* Upgrade Font Awesome to the latest version
* Upgrade Chartist to 0.8.3
* Update the code to comply with the linter rules

### CODE REVIEW

**Comment by mojavelinux** [comment]
I've been using eslint on a new project and I'm really liking it.

Have you considered using the Standard.js profile for eslint? It's a little opinionated, but I find it lets me focus on the code more. I still customize a few rules, but most are aligned.

**Comment by Mogztter** [comment]
@mojavelinux Thanks for the suggestion, I've switched to standard.js :+1:

**Comment by Mogztter** [comment]
I'm fully aware that this pull request touches a lot of subjects. I should probably create one pull request per subject. @mojavelinux What do you think ?

**Comment by Mogztter** [comment]
Changes merged as part of pull requests: #172, #173, #174, #175, #176 and #177

**Pull request closed without merging**
