### PR TITLE
Add missing images from Riak theme

### PR DESCRIPTION
**Pull request by ssebastianj**
I took an extra step to convert the images from `.jpg` to `.png` (using [Zamzar](http://www.zamzar.com/)) and then compress them (using [TinyPNG](https://tinypng.com/)).

### CODE REVIEW

**Comment by mojavelinux** [comment]
Thanks!

**Comment by Mogztter** [comment]
Thanks @ssebastianj :+1:

**Comment by Mogztter** [comment]
I've just tested it, this looks great :)

**Comment by ssebastianj** [comment]
Glad to hear that! I'm looking forward to see the update on the Chrome Web Store :smiley:

**Comment by Mogztter** [comment]
I will do it soon, I just want to fix a few more issues before publishing a new version :wink:

**Pull request merged**
